// Code generated by "stringer -output=name_visibility_setting_string.go -type=NameVisibilitySetting -linecomment"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ShowInDMsOnly-0]
	_ = x[Show-1]
	_ = x[Hide-2]
}

const _NameVisibilitySetting_name = "SHOW_IN_DMS_ONLYSHOWHIDE"

var _NameVisibilitySetting_index = [...]uint8{0, 16, 20, 24}

func (i NameVisibilitySetting) String() string {
	if i < 0 || i >= NameVisibilitySetting(len(_NameVisibilitySetting_index)-1) {
		return "NameVisibilitySetting(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NameVisibilitySetting_name[_NameVisibilitySetting_index[i]:_NameVisibilitySetting_index[i+1]]
}
