name: Change Log

on: [push]

jobs:
  changelog:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate changelog
        run: git log $(git describe --always --abbrev=0 --tags $(git describe --abbrev=0 --tags --always)^)..HEAD --oneline --pretty="- %s" > CHANGELOG.md
      - name: Upload changelog
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
