name: Deploy

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16.5
      - name: Test
        run: go test ./...
      - name: Build
        run: go build

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - name: Use Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16.5
      - name: Build
        run: go build
      - name: SCP
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: ./BoostRequestBot
          target: release
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: screen -dm bash -c "./update"

  changelog:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - name: Generate changelog
        run: git log $(git describe --always --abbrev=0 --tags $(git describe --abbrev=0 --tags --always)^)..HEAD --oneline --pretty="- %s" > CHANGELOG.md
      - name: Upload changelog
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  generate-sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
      - name: Download openapi-generator-cli
        run: wget https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/5.1.0/openapi-generator-cli-5.1.0.jar -O openapi-generator-cli.jar
      - name: Make sdk dir
        run: mkdir sdk_zip
      - name: Build Python sdk
        run: |
          VERSION=$(echo $GITHUB_REF | sed -E "s/\/?refs\/tags\/v?//g")
          echo packageVersion: $VERSION >> openapi-config-python.yml
          java -jar openapi-generator-cli.jar generate -i openapi.yml -g python -o python_sdk --package-name boostrequestbotapi --config openapi-config-python.yml
          zip -r sdk_zip/BoostRequestBot_Python_SDK.zip python_sdk
        env:
          GITHUB_REF: github.ref
      - name: Upload
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: sdk_zip/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
