name: Deploy

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17.2
      - name: Test
        run: go test ./...
      - name: Build
        run: go build

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - name: Use Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17.2
      - name: Build
        run: go build
      - name: SCP
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: ./BoostRequestBot
          target: release
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: screen -dm bash -c "./update"

  changelog:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate changelog
        run: git log $(git describe --always --abbrev=0 --tags $(git describe --abbrev=0 --tags --always)^)..HEAD --oneline --pretty="- %s" > CHANGELOG.md
      - name: Upload changelog
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  generate-sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python SDK generator configuration
        run: |
          VERSION=$(echo $GITHUB_REF | sed -E "s/\/?refs\/tags\/v?//g")
          echo packageVersion: $VERSION >> openapi-config-python.yml
        env:
          GITHUB_REF: github.ref

      - name: Generate Python SDK
        run: |
          docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate \
            -i /local/openapi.yml \
            -g python \
            -c /local/openapi-config-python.yml \
            -o /local/python_sdk \
            --package-name boostrequestbotapi
          sudo chown -R $USER:$USER python_sdk

      - name: Generate Docs
        run: |
          docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate \
            -i /local/openapi.yml \
            -g markdown \
            -o /local/docs
          sudo chown -R $USER:$USER python_sdk

      - name: Zip
        run: |
          mkdir sdk_zip
          zip -r sdk_zip/BoostRequestBot_Python_SDK.zip python_sdk
          zip -r sdk_zip/Markdown_Docs.zip docs
      - name: Upload
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: sdk_zip/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
